# Generated by Django 5.0 on 2026-05-28 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='单位')),
                ('lab_group', models.CharField(blank=True, max_length=255, verbose_name='课题组')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('research_direction', models.CharField(blank=True, max_length=500, verbose_name='研究方向')),
                ('status', models.CharField(choices=[('potential', '潜在客户'), ('active', '活跃客户'), ('inactive', '沉睡客户'), ('lost', '流失客户')], default='potential', max_length=20, verbose_name='客户状态')),
                ('source', models.CharField(choices=[('wechat', '微信介绍'), ('xiaohongshu', '小红书'), ('xianyu', '咸鱼'), ('taobao', '淘宝'), ('dealer', '经销商介绍'), ('other', '其他')], default='other', max_length=20, verbose_name='客户来源')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_type', models.CharField(choices=[('wechat', '微信'), ('phone', '电话'), ('email', '邮件'), ('visit', '上门拜访'), ('other', '其他')], max_length=20, verbose_name='跟进方式')),
                ('content', models.TextField(verbose_name='跟进内容')),
                ('next_action', models.CharField(blank=True, max_length=500, verbose_name='下次行动')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='下次跟进日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='crm.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '跟进记录',
                'verbose_name_plural': '跟进记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
