# Generated by Django 5.0 on 2026-06-02 01:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='品牌名称')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='英文名')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='产地')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌管理',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='default_shipping_address',
            field=models.TextField(blank=True, verbose_name='常用收货地址'),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_shipping_contact',
            field=models.CharField(blank=True, max_length=50, verbose_name='收货联系人'),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_shipping_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='收货电话'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='注册地址'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_bank',
            field=models.CharField(blank=True, max_length=100, verbose_name='开户行'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_bank_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='银行账号'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='注册电话'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_tax_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='纳税人识别号'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='发票抬头'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='订单编号')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='订单日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('purchasing', '采购中'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='订单状态')),
                ('shipping_contact', models.CharField(blank=True, max_length=50, verbose_name='收货联系人')),
                ('shipping_phone', models.CharField(blank=True, max_length=50, verbose_name='收货电话')),
                ('shipping_address', models.TextField(blank=True, verbose_name='收货地址')),
                ('shipping_method', models.CharField(blank=True, choices=[('sf_normal', '顺丰普通'), ('sf_reagent', '顺丰试剂'), ('sf_cold', '顺丰冷链'), ('ems', 'EMS'), ('jd', '京东快递'), ('zto', '中通快递'), ('pickup', '自提'), ('other', '其他')], default='sf_normal', max_length=20, verbose_name='发货方式')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='快递单号')),
                ('shipped_date', models.DateField(blank=True, null=True, verbose_name='发货日期')),
                ('invoice_type', models.CharField(choices=[('none', '不开票'), ('normal', '普通发票'), ('vat', '增值税专用发票')], default='normal', max_length=20, verbose_name='发票类型')),
                ('invoice_status', models.CharField(choices=[('pending', '待开票'), ('issued', '已开票'), ('not_required', '无需开票')], default='pending', max_length=20, verbose_name='开票状态')),
                ('invoice_title', models.CharField(blank=True, max_length=200, verbose_name='发票抬头')),
                ('invoice_tax_id', models.CharField(blank=True, max_length=50, verbose_name='纳税人识别号')),
                ('invoice_bank', models.CharField(blank=True, max_length=100, verbose_name='开户行')),
                ('invoice_bank_account', models.CharField(blank=True, max_length=100, verbose_name='银行账号')),
                ('invoice_address', models.CharField(blank=True, max_length=200, verbose_name='注册地址')),
                ('invoice_phone', models.CharField(blank=True, max_length=50, verbose_name='注册电话')),
                ('invoice_email', models.EmailField(blank=True, max_length=254, verbose_name='发票邮箱')),
                ('invoice_remark', models.CharField(blank=True, max_length=200, verbose_name='开票备注')),
                ('payment_term', models.CharField(choices=[('prepay', '款到发货'), ('cod', '货到付款'), ('monthly_30', '月结30天'), ('monthly_60', '月结60天'), ('other', '其他')], default='prepay', max_length=20, verbose_name='付款方式')),
                ('payment_method', models.CharField(blank=True, choices=[('transfer', '银行转账'), ('alipay', '支付宝'), ('wechat', '微信'), ('cash', '现金'), ('monthly', '月结'), ('other', '其他')], default='transfer', max_length=20, verbose_name='结算方式')),
                ('payment_status', models.CharField(choices=[('unpaid', '未付款'), ('partial', '部分付款'), ('paid', '已付款')], default='unpaid', max_length=20, verbose_name='付款状态')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='运费(元)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额(元)')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='实际金额(元)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已付金额(元)')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.customer', verbose_name='客户')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='业务员')),
            ],
            options={
                'verbose_name': '销售订单',
                'verbose_name_plural': '订单管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='回款金额(元)')),
                ('method', models.CharField(choices=[('transfer', '银行转账'), ('alipay', '支付宝'), ('wechat', '微信'), ('cash', '现金'), ('other', '其他')], default='transfer', max_length=20, verbose_name='付款方式')),
                ('payment_date', models.DateField(verbose_name='回款日期')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.order', verbose_name='订单')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '回款记录',
                'verbose_name_plural': '回款记录',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('reagent', '试剂'), ('consumable', '耗材'), ('kit', '试剂盒'), ('antibody', '抗体'), ('instrument', '仪器设备'), ('other', '其他')], default='reagent', max_length=20, verbose_name='产品类别')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
                ('catalog_number', models.CharField(max_length=100, unique=True, verbose_name='货号')),
                ('cas_number', models.CharField(blank=True, max_length=50, verbose_name='CAS号')),
                ('spec', models.CharField(max_length=100, verbose_name='规格/包装')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='销售单位')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成本价(元)')),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='目录价(元)')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='标准售价(元)')),
                ('storage', models.CharField(choices=[('rt', '室温'), ('4', '4°C'), ('-20', '-20°C'), ('-80', '-80°C'), ('ln2', '液氮')], default='4', max_length=10, verbose_name='存储条件')),
                ('lead_time', models.IntegerField(default=7, verbose_name='货期(工作日)')),
                ('is_active', models.BooleanField(default=True, verbose_name='在售')),
                ('description', models.TextField(blank=True, verbose_name='产品描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.brand', verbose_name='品牌')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品目录',
                'ordering': ['brand', 'catalog_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('catalog_number', models.CharField(max_length=100, verbose_name='货号')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('spec', models.CharField(blank=True, max_length=100, verbose_name='规格')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价(元)')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成本价(元)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=13, max_digits=5, verbose_name='税率(%)')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.order', verbose_name='订单')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
            },
        ),
    ]
