# Generated by Django 5.0 on 2026-06-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_brand_customer_default_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['brand__name', 'catalog_number'], 'verbose_name': '产品', 'verbose_name_plural': '产品目录'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell_price',
        ),
        migrations.AddField(
            model_name='product',
            name='dealer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='经销商价(元)'),
        ),
        migrations.AddField(
            model_name='product',
            name='terminal_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='终端价(元)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_status',
            field=models.CharField(choices=[('pending', '待开票'), ('submitted', '已递交财务'), ('issued', '已开票'), ('not_required', '无需开票')], default='pending', max_length=20, verbose_name='开票状态'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='经销商价(元)'),
        ),
    ]
