# Generated by Django 5.0 on 2026-06-03 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_product_options_remove_product_cost_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='分组名称')),
                ('group_type', models.CharField(choices=[('lab', '课题组'), ('company', '公司/企业'), ('hospital', '医院'), ('other', '其他')], default='lab', max_length=20, verbose_name='分组类型')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='所属单位')),
                ('pi_name', models.CharField(blank=True, max_length=100, verbose_name='负责人/PI')),
                ('pi_phone', models.CharField(blank=True, max_length=50, verbose_name='负责人电话')),
                ('pi_email', models.EmailField(blank=True, max_length=254, verbose_name='负责人邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '客户分组',
                'verbose_name_plural': '客户分组管理',
                'ordering': ['group_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='custom_discount',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='留空则使用等级默认折扣，填写则覆盖', max_digits=5, null=True, verbose_name='自定义折扣(%)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('research', '科研终端'), ('industrial', '工业终端'), ('dealer', '经销商')], default='research', max_length=20, verbose_name='客户类型'),
        ),
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.CharField(choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级'), ('D', 'D级'), ('E', 'E级')], default='C', max_length=1, verbose_name='客户等级'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=100, max_digits=5, verbose_name='折扣(%)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='目录价(元)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交单价(元)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='crm.customergroup', verbose_name='所属分组'),
        ),
        migrations.CreateModel(
            name='DiscountLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('research', '科研终端'), ('industrial', '工业终端'), ('dealer', '经销商')], max_length=20, verbose_name='客户类型')),
                ('level', models.CharField(choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级'), ('D', 'D级'), ('E', 'E级')], max_length=1, verbose_name='等级')),
                ('description', models.CharField(blank=True, help_text='如：回款周期30天内、年采购额5万以上等', max_length=200, verbose_name='等级说明')),
                ('default_discount', models.DecimalField(decimal_places=1, default=100, help_text='100=无折扣，90=九折，85=八五折', max_digits=5, verbose_name='默认折扣(%)')),
            ],
            options={
                'verbose_name': '折扣等级',
                'verbose_name_plural': '折扣等级管理',
                'ordering': ['customer_type', 'level'],
                'unique_together': {('customer_type', 'level')},
            },
        ),
        migrations.CreateModel(
            name='BrandDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('research', '科研终端'), ('industrial', '工业终端'), ('dealer', '经销商')], max_length=20, verbose_name='客户类型')),
                ('level', models.CharField(choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级'), ('D', 'D级'), ('E', 'E级')], max_length=1, verbose_name='等级')),
                ('discount', models.DecimalField(decimal_places=1, default=100, max_digits=5, verbose_name='折扣(%)')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='crm.brand', verbose_name='品牌')),
            ],
            options={
                'verbose_name': '品牌折扣',
                'verbose_name_plural': '品牌折扣设置',
                'ordering': ['brand', 'customer_type', 'level'],
                'unique_together': {('brand', 'customer_type', 'level')},
            },
        ),
    ]
